import { NgModule } from '@angular/core';
import {
  MatListModule,
  MatIconModule,
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatTabsModule,
  MatToolbarModule,
  MatDividerModule,
  MatSelectModule,
  MatTableModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatProgressBarModule,
  MatDialogModule,
  MatRadioModule,
  MatExpansionModule,
  MatSlideToggleModule,
  MatPaginatorModule,
  MatChipsModule,
  MatMenuModule,
  MatButtonToggleModule,
  MatSnackBarModule,
  MatTooltipModule,
  MatAutocompleteModule,
  MatSidenavModule,
} from '@angular/material';

const matModules = [
  MatListModule,
  MatButtonModule,
  MatIconModule,
  MatFormFieldModule,
  MatInputModule,
  MatTabsModule,
  MatToolbarModule,
  MatDividerModule,
  MatSelectModule,
  MatTableModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatProgressBarModule,
  MatExpansionModule,
  MatMenuModule,
  MatChipsModule,
  MatPaginatorModule,
  MatSlideToggleModule,
  MatProgressBarModule,
  MatDialogModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatRadioModule,
  MatCheckboxModule,
  MatExpansionModule,
  MatButtonToggleModule,
  MatSnackBarModule,
  MatTooltipModule,
  MatAutocompleteModule,
  MatSidenavModule
];
@NgModule({
  imports: matModules,
  exports: matModules
})
export class MaterialModule {}
